<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Equipe extends \App\Entity\Equipe implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'chantiers' => [parent::class, 'chantiers', null],
        "\0".parent::class."\0".'chef_equipe' => [parent::class, 'chef_equipe', null],
        "\0".parent::class."\0".'competence_equipe' => [parent::class, 'competence_equipe', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nom_equipe' => [parent::class, 'nom_equipe', null],
        "\0".parent::class."\0".'nombre' => [parent::class, 'nombre', null],
        "\0".parent::class."\0".'ouvriers' => [parent::class, 'ouvriers', null],
        'chantiers' => [parent::class, 'chantiers', null],
        'chef_equipe' => [parent::class, 'chef_equipe', null],
        'competence_equipe' => [parent::class, 'competence_equipe', null],
        'id' => [parent::class, 'id', null],
        'nom_equipe' => [parent::class, 'nom_equipe', null],
        'nombre' => [parent::class, 'nombre', null],
        'ouvriers' => [parent::class, 'ouvriers', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
