<?php

namespace Container04wlIJ2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAffectationControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TgqcLbw.App\Controller\AffectationController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TgqcLbw.App\\Controller\\AffectationController::delete()'] = ($container->privates['.service_locator.TgqcLbw'] ?? $container->load('get_ServiceLocator_TgqcLbwService'))->withContext('App\\Controller\\AffectationController::delete()', $container);
    }
}
