<?php

namespace Container04wlIJ2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAffectationControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4Vg_H9_.App\Controller\AffectationController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4Vg_H9_.App\\Controller\\AffectationController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'affectation' => ['privates', '.errored..service_locator.4Vg_H9_.App\\Entity\\Affectation', NULL, 'Cannot autowire service ".service_locator.4Vg_H9_": it needs an instance of "App\\Entity\\Affectation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'affectation' => 'App\\Entity\\Affectation',
        ]))->withContext('App\\Controller\\AffectationController::show()', $container);
    }
}
