<?php

namespace Container04wlIJ2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChantierControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.R6B8D0X.App\Controller\ChantierController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.R6B8D0X.App\\Controller\\ChantierController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'chantier' => ['privates', '.errored..service_locator.R6B8D0X.App\\Entity\\Chantier', NULL, 'Cannot autowire service ".service_locator.R6B8D0X": it needs an instance of "App\\Entity\\Chantier" but this type has been excluded in "config/services.yaml".'],
        ], [
            'chantier' => 'App\\Entity\\Chantier',
        ]))->withContext('App\\Controller\\ChantierController::show()', $container);
    }
}
