<?php

namespace Container04wlIJ2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOuvrierControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0f_Qx9L.App\Controller\OuvrierController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0f_Qx9L.App\\Controller\\OuvrierController::delete()'] = ($container->privates['.service_locator.0f_Qx9L'] ?? $container->load('get_ServiceLocator_0fQx9LService'))->withContext('App\\Controller\\OuvrierController::delete()', $container);
    }
}
