<?php

namespace ContainerJI2VEiJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEquipeControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0nXLR3y.App\Controller\EquipeController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0nXLR3y.App\\Controller\\EquipeController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'equipe' => ['privates', '.errored..service_locator.0nXLR3y.App\\Entity\\Equipe', NULL, 'Cannot autowire service ".service_locator.0nXLR3y": it needs an instance of "App\\Entity\\Equipe" but this type has been excluded in "config/services.yaml".'],
        ], [
            'equipe' => 'App\\Entity\\Equipe',
        ]))->withContext('App\\Controller\\EquipeController::show()', $container);
    }
}
