<?php

namespace ContainerJI2VEiJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOuvrierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.0f_Qx9L.App\Entity\Ouvrier' shared service.
     *
     * @return \App\Entity\Ouvrier
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0f_Qx9L": it needs an instance of "App\\Entity\\Ouvrier" but this type has been excluded in "config/services.yaml".');
    }
}
