<?php

namespace ContainerMklr0vD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CbpT37NService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CbpT37N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CbpT37N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'equipe' => ['privates', '.errored..service_locator.CbpT37N.App\\Entity\\Equipe', NULL, 'Cannot autowire service ".service_locator.CbpT37N": it needs an instance of "App\\Entity\\Equipe" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'equipe' => 'App\\Entity\\Equipe',
            'entityManager' => '?',
        ]);
    }
}
