<?php

namespace ContainerMklr0vD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0fQx9LService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0f_Qx9L' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0f_Qx9L'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ouvrier' => ['privates', '.errored..service_locator.0f_Qx9L.App\\Entity\\Ouvrier', NULL, 'Cannot autowire service ".service_locator.0f_Qx9L": it needs an instance of "App\\Entity\\Ouvrier" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'ouvrier' => 'App\\Entity\\Ouvrier',
            'entityManager' => '?',
        ]);
    }
}
