<?php

namespace Container7uHgWpm;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOuvrierControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p1i6NoX.App\Controller\OuvrierController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p1i6NoX.App\\Controller\\OuvrierController::index()'] = ($container->privates['.service_locator.p1i6NoX'] ?? $container->load('get_ServiceLocator_P1i6NoXService'))->withContext('App\\Controller\\OuvrierController::index()', $container);
    }
}
