<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Ouvrier extends \App\Entity\Ouvrier implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'affectations' => [parent::class, 'affectations', null],
        "\0".parent::class."\0".'competance' => [parent::class, 'competance', null],
        "\0".parent::class."\0".'equipe' => [parent::class, 'equipe', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'nom_ouvrier' => [parent::class, 'nom_ouvrier', null],
        "\0".parent::class."\0".'planning' => [parent::class, 'planning', null],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null],
        'affectations' => [parent::class, 'affectations', null],
        'competance' => [parent::class, 'competance', null],
        'equipe' => [parent::class, 'equipe', null],
        'id' => [parent::class, 'id', null],
        'nom_ouvrier' => [parent::class, 'nom_ouvrier', null],
        'planning' => [parent::class, 'planning', null],
        'role' => [parent::class, 'role', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
