<?php

namespace ContainerWl8BQru;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEquipeControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\EquipeController' shared autowired service.
     *
     * @return \App\Controller\EquipeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/EquipeController.php';

        $container->services['App\\Controller\\EquipeController'] = $instance = new \App\Controller\EquipeController();

        $instance->setContainer(($container->privates['.service_locator.ZyP9f7K'] ?? $container->load('get_ServiceLocator_ZyP9f7KService'))->withContext('App\\Controller\\EquipeController', $container));

        return $instance;
    }
}
