<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGonf2k1\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGonf2k1/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerGonf2k1.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerGonf2k1\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerGonf2k1\App_KernelTestDebugContainer([
    'container.build_hash' => 'Gonf2k1',
    'container.build_id' => '99e93012',
    'container.build_time' => 1741268579,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGonf2k1');
