<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP6yZxDS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP6yZxDS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP6yZxDS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP6yZxDS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP6yZxDS\App_KernelDevDebugContainer([
    'container.build_hash' => 'P6yZxDS',
    'container.build_id' => 'a6ca2db0',
    'container.build_time' => 1741190133,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP6yZxDS');
