<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMklr0vD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMklr0vD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMklr0vD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMklr0vD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMklr0vD\App_KernelDevDebugContainer([
    'container.build_hash' => 'Mklr0vD',
    'container.build_id' => 'fc64acd3',
    'container.build_time' => 1741103117,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMklr0vD');
